version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/content:/app/content
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - qualityplaybook

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:8000/api
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - qualityplaybook

networks:
  qualityplaybook:
    driver: bridge
